### ISSUE TITLE
Dropdown options are left in background

### ISSUE THREAD

**Issue by travisyeh** [alinz/react-native-dropdown#1]
Hi! Thanks for this component; it looks great. The only problem is that I'm creating a form that uses one dropdown per row of the form. When they're stacked vertically, the options show up behind the other elements like so: 
![image](https://cloud.githubusercontent.com/assets/6694308/9239987/83331082-412f-11e5-96c5-7384800a4db4.png)

(In this picture, the second-to-last dropdown titled "Test4" is selected. Note how the options display underneath the dropdown below it). 

Is there any way to make the options appear above the other elements? Thanks!

**Comment by alinz** [comment]
@travisyeh Thanks for testing it. I haven't tried this way. I might have a solution but I need one or two days to implement the new version. I will get back to you once I have something. Again thank you!

**Comment by travisyeh** [comment]
Sweet, thanks for the quick reply!

**Comment by wheycool** [comment]
I'm having the same issue.

**Comment by alinz** [comment]
@travisyeh @wheycool sorry for a long delay, It has been fixed, I had to changed some api because there is proper way of doing this. please take a look at the example.
