### ISSUE TITLE
How do I change style of Option Component?

### ISSUE THREAD

**Issue by melihmucuk** [alinz/react-native-dropdown#12]
Please add styling sample to example.

**Comment by pakistan** [comment]
Having the Same Issue. I want to be able to center the text within the box and make the dropdown not translucent. (As below the text below the dropdown can be seen.)
![image](https://cloud.githubusercontent.com/assets/11988989/11222188/17fe32b6-8d37-11e5-8cf3-399d9b39d2c3.png)

**Comment by pakistan** [comment]
I was able to align the text with alignItems attribute in flex. Still not entirely sure how to fix the translucency.

**Comment by gs-akhan** [comment]
Hi @adnanzaib You can pass "style" property to the <Option /> as it accepts that as props .. Now I see the problem with overflow ? is that right ? 
Please share example code I will be more than happy to assist..
:)

**Comment by gs-akhan** [comment]
@melihmucuk I am updating readme this week.
Thanks
