### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by flyingmate** [alinz/react-native-dropdown#13]
Does it work on Android? There's an index.android.js file but it's only containing default code.

**Comment by flyingmate** [comment]
I checked it's working on Android.

**Comment by BasitAli** [comment]
Doesn't work for me on Android. updatePosition for OptionList returns undefined for all values.

**Comment by gs-akhan** [comment]
@BasitAli this is a known issue. Unfortunately we aren't able to fix. May be you can give it a try.

**Comment by BasitAli** [comment]
I am playing with the onLayout events to get this to work. I'll push in a fix when it's working.
