### ISSUE TITLE
OptionList background is transparent

### ISSUE THREAD

**Issue by httnn** [alinz/react-native-dropdown#14]
...and there doesn't seem to be a way to set one

<img width="165" alt="screen shot 2015-12-02 at 16 35 25" src="https://cloud.githubusercontent.com/assets/7894563/11533726/da34ec2a-9913-11e5-9412-474d8ba42fb7.png">

I'm using RN 0.15.0

**Comment by httnn** [comment]
oh, so apparently the parent of `OptionList` needs to have a `backgroundColor` set, strange. well, the problem is resolved now!

**Comment by marsprince** [comment]
@bodyflex Same problem.Can you make a simple example code for solution?Thank you!

**Comment by httnn** [comment]
just set `backgroundColor` to any color on the parent of `OptionList`

```
<View style={{backgroundColor: '#fff'}}>
    ...
    <OptionList />
</View>
```

**Comment by marsprince** [comment]
@bodyflex Thank you,guys

**Comment by amibition521** [comment]
@marsprince @bodyflex  When I set the parent component of the background color, lead to cannot click on the select, there's no way to change the background color optionlist
![trans](https://cloud.githubusercontent.com/assets/13275317/12215464/aa71ff2a-b6f8-11e5-8cc2-530845373f22.png)
![transplent](https://cloud.githubusercontent.com/assets/13275317/12215465/aac9f7a2-b6f8-11e5-84d9-cf7e4ab87c8b.png)

**Comment by xumine** [comment]
@amibition521 Put the Select component to the last may help.

**Comment by shashankkulshresthas** [comment]
Hi,
Thanks for update.
How can I set foreground color on each option? Please suggest.
