### ISSUE TITLE
Error while:  npm install

### ISSUE THREAD

**Issue by cspkop** [alinz/react-native-dropdown#17]
I got below error while installing the package, How to resolve this?
![image](https://cloud.githubusercontent.com/assets/10728316/11738652/b876355a-a00a-11e5-8ab8-d40def89bdd1.png)

**Comment by gs-akhan** [comment]
Hi . are you trying to install this into some deep "node_module" folder. I tried installing it just installs fine.. 
You should be installing this in the root folder of react native app.

Thanks

**Comment by cspkop** [comment]
@gs-akhan  - Yeah...thats the root folder of my React-Native app on H: drive. Its just that it resides deep inside my organized folders. :)

**Comment by gs-akhan** [comment]
@cspkop . Actually this library is pure JS it does'nt have to to do "node-gyp rebuild" This is weird. 
Do you have other dependencies too in package.json ?

**Comment by cspkop** [comment]
@gs-akhan 
Below is the content of my React-Native apps package.json file, seems like it has added this package as dependency and then got this error.
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "react-native": "0.16.0",
    "react-native-dropdown": "0.0.6"
  }
}

**Comment by gs-akhan** [comment]
@cspkop Try including it and run the example, if that works - it should be ok.  I will try to run this into react native 0.0.16. which I havent done so far. 
Thanks

**Comment by cspkop** [comment]
@gs-akhan - I tried 'require'ing the files in my app as shown in the example, and it works fine.
 But, now the UI is getting rendered incorrectly... have a look at the  below screenshots

![snap-landscape](https://cloud.githubusercontent.com/assets/10728316/11742026/c69cac5a-a022-11e5-92c0-40c84451c9bd.png)
![snap-portrait](https://cloud.githubusercontent.com/assets/10728316/11742025/c69b98b0-a022-11e5-887e-b6078476424a.png)

**Comment by gs-akhan** [comment]
@cspkop  Ouch !! Looks like issue on Android. I shall look into this .. 
Will fix it ASAP..

**Comment by gs-akhan** [comment]
@cspkop If you can lookinto it please send a PR.

**Comment by gs-akhan** [comment]
@alinz I did spend like hours behind this. what I observe is that, the setTimeout callbacks in updatePosition function doesn't get executed at all.. Any idea why ?
Thanks

**Comment by gs-akhan** [comment]
@cspkop Well I have investigated this and found that it might be a platform issue from React-Native Android. "UIManager.measure" doesn't give proper values to position the dropdown right under the select. 
@alinz  What I can do is position this selection at center of screen for Android . At least the users can have it working. need your word on this. 
Thanks.

**Comment by alinz** [comment]
@gs-akhan give me one more day. I will take a look at it. Will let you know.

**Comment by sankhadeeproy007** [comment]
Hi, any updates on the positioning thing? I'd have looked into it. But I'm just starting out and have very little knowledge. Any progress?
