### ISSUE TITLE
Options rendered unaligned with dropdown

### ISSUE THREAD

**Issue by jlugner** [alinz/react-native-dropdown#22]
Getting a strange behavior when using 0.0.6. The options are rendered with quite an offset. Looks like this when running the example code from the readme:

![screenshot_2016-01-07-13-27-00](https://cloud.githubusercontent.com/assets/1486169/12170539/a5218cf0-b542-11e5-89f6-10fa10c21f10.png)

**Comment by gs-akhan** [comment]
@Pungsnigel 
Hi, this is a know issue on Android. And still we couldn;t resolve it ..

**Comment by jlugner** [comment]
No idea how to fix?

**Comment by gs-akhan** [comment]
Nops. I will give it a try on weekend though.

**Comment by jlugner** [comment]
Great, thanks. Let me know if I can help out.

**Comment by gs-akhan** [comment]
Sure. As you are using on Android if you can figure anyways to fix it
please send pr. I will merge it .
Thanks

**Comment by UKDeveloper99** [comment]
Having this exact same problem, is this fixed yet @gs-akhan ?

**Comment by UKDeveloper99** [comment]
I found it renderered in the correct position if I took away the styles for the <View> container that contains the dropdown in the example code.

Remove alignItems style and justifyContent. One of those must be responsible for this bug.

**Comment by shivangbtech** [comment]
Problem is solved after removing 'justifyContent: 'center', alignItems: 'center' ' but now how can we align the component. I need it in center of screen.

**Comment by skeie** [comment]
@shivangbtech You can wrap the `select` component in a View like this:
`<View style={{flex: 1, justifyContent: 'center', alignSelf: 'center'}}>`
