### ISSUE TITLE
RCTUIManager.measure could not be processed.

### ISSUE THREAD

**Issue by amibition521** [alinz/react-native-dropdown#23]
When implementing this component in my Android app this error comes up.
I have done the same steps as in the example; 
Using ReactNative 0.17.0.
code:
![xxw gvr5321 3 lig7srip](https://cloud.githubusercontent.com/assets/13275317/12190939/780f8934-b609-11e5-8458-5608fc62fb2b.png)
![_vuxxi3 r _izzh6 ws 7q](https://cloud.githubusercontent.com/assets/13275317/12190942/80781398-b609-11e5-86d9-db283c1bc5d4.png)
![_39 mpjug 6h6cpc jkla2](https://cloud.githubusercontent.com/assets/13275317/12190952/8da7025e-b609-11e5-81cc-bed29ca7dccb.png)

**Comment by amibition521** [comment]
I write in render() function ,it work.but,in renderScene (route,navigator) function ,it isn't work.please help me.
![dropdown](https://cloud.githubusercontent.com/assets/13275317/12194767/407f2794-b62d-11e5-8aff-9191ce10574e.png)

**Comment by UKDeveloper99** [comment]
see my answer here 
https://github.com/alinz/react-native-dropdown/issues/10
@amibition521
