### ISSUE TITLE
Allow Option to have styled text.

### ISSUE THREAD

**Issue by yapcheahshen** [alinz/react-native-dropdown#25]
please allow option to have styled text.

https://github.com/alinz/react-native-dropdown/blob/master/lib/option.js#L33

change from 
children: React.PropTypes.string.isRequired
to
children: React.PropTypes.node.isRequired

**Comment by gs-akhan** [comment]
Hi,
You can pass `styleText` to option to get it styled. 
Thanks

**Comment by yapcheahshen** [comment]
ok!

**Comment by gs-akhan** [comment]
Give it a short and let me know if it works. :)

**Comment by yapcheahshen** [comment]
this is what I need, so styleText cannot work.

&lt;Option>&lt;Text>normal&lt;Text style={{color:'red'}}>hilite&lt;/Text>&lt;/Text>&lt;/Option>

**Comment by gs-akhan** [comment]
Ouch !! We need a enhancement .. I am ok with your idea of passing node as children .
@alinz Need your word on this change ? Thanks
