### ISSUE TITLE
Argument 0 (NSNumber) of RCTUIManager.measure must not be null

### ISSUE THREAD

**Issue by krjw** [alinz/react-native-dropdown#26]
I basically copied your example into a scrollview in a navigatorIOS component. It shows me this error. I guess it is the updatePosition function of your package which causes the error. Any suggestions? I am new to rn.

Greetings,
i7clock

**Comment by krjw** [comment]
Ok i looked at your updatePosition function and its pretty cool and def not the problem. I guess I rendered a loading view where the refs were not available yet. This caused the error.. closing this!

**Comment by UKDeveloper99** [comment]
https://github.com/alinz/react-native-dropdown/issues/10
see my answer here, you're basically right @i7clock
