### ISSUE TITLE
Tapping outside the dropdown doesn't hide the dropdown menu

### ISSUE THREAD

**Issue by pickhardt** [alinz/react-native-dropdown#3]
Hey, thanks for making this.

Once you've dropped down the menu, tapping outside the menu should hide the menu, but it doesn't do anything.

I'm not sure how to do this in an elegant way. Any ideas? This would be important because users are going to complain if it doesn't work that way.

**Comment by wheycool** [comment]
I agree and am having the same issue. @pickhardt – did you come up with any solutions?

**Comment by pickhardt** [comment]
No, I just don't use the dropdown. I used an action sheet.

**Comment by alinz** [comment]
@pickhardt @wheycool I have fixed the problem. You can use v0.0.3 instead.

**Comment by jlugner** [comment]
Having the same problem now. Using version 0.0.6.

**Comment by gs-akhan** [comment]
Let me check this ..

**Comment by alinz** [comment]
I'm trying to find a time to help you @gs-akhan out on this issue. Need to finish couple of my tasks and I will get back helping you. Thanks for all the help

**Comment by otech47** [comment]
Any update on this?
