### ISSUE TITLE
Is there a way to edit backgroundColor of overlay?

### ISSUE THREAD

**Issue by michaelgifford** [alinz/react-native-dropdown#30]
When I change the backgroundColor of overlay from overlay.js it works and changes the background color of the dropdown, but when I change the backgroundColor of the view, select, option, optionlist, etc. within the render() function the backgroundColor doesn't change. Trying to get a white background on the dropdown as opposed to transparent. Thanks.

**Comment by joshbedo** [comment]
Having the same issue

**Comment by gs-akhan** [comment]
Hi, this is not possible as of now. I will be making this fix in  a day or so .. :)

**Comment by kesha-antonov** [comment]
Will this PR solve your problems? https://github.com/alinz/react-native-dropdown/pull/33

**Comment by WilsonChiang** [comment]
@kesha-antonov Looks like its still transparent for me if theres items beneath, but the background color does change.

**Comment by joshbedo** [comment]
I have a fix for this, I just tested it in my project.
