### ISSUE TITLE
Option list not displaying correctly

### ISSUE THREAD

**Issue by alexprice1** [alinz/react-native-dropdown#37]
![screen shot 2016-03-18 at 5 58 55 pm](https://cloud.githubusercontent.com/assets/4140149/13894180/431aaf4a-ed33-11e5-9ec4-44e4e60f24f2.png)

**Comment by alexprice1** [comment]
`Time` and `Time` are both dropdowns, but their "active" status is being hidden under other items.

**Comment by alexprice1** [comment]
<img width="445" alt="screen shot 2016-03-19 at 10 54 33 am" src="https://cloud.githubusercontent.com/assets/4140149/13899633/26c00366-edc1-11e5-9aec-0e455fe226ac.png">
Also placement seems off on android

**Comment by agrass** [comment]
Same problem. someone started working in one workaround for this?

**Comment by alexprice1** [comment]
@agrass I had commented in this issue pertaining to this dropdown issue:

https://github.com/facebook/react-native/issues/698

It appears that this cannot be achieved with the current implementation of react-native. I did have an idea of adding a component at the very end of my component hierarchy, and just moving that based off of what selector is pressed, but this seems like overkill. I'm still in development and hoping the issue is fixed before Alpha.

**Comment by purnomoeko** [comment]
@alexprice91 
I made pull request for this see https://github.com/alinz/react-native-dropdown/pull/38/commits/1064cee0c45ccd4a3d39faa07cbe9b723d1e7ff7

actually it's just easy step, just add background colour to the items.js file.  and the you have to make sure the Options List in the root tag. 

See my example: 

```
<ScrollView>
   <View>
          <Text style={styles.labelText} >Attendance Type</Text>
          <Select
            style={{width: 500}}
            width={500}
            ref="selectType"
            optionListRef={this._getOptionList.bind(this)}
            defaultValue="Select Type..."
            onSelect={this._change.bind(this)}
            >
            <Option>Roll Call</Option>
            <Option>Boys Awake</Option>
            <Option>Led Player</Option>
            <Option>Out For Mass</Option>
            <Option>Attendance</Option>
          </Select>

          <Text style={styles.labelText}>Time </Text>
          <DatePickerIOS
            date={this.state.date}
            mode="time"
            timeZoneOffsetInMinutes={this.state.timeZoneOffsetInHours * 60}
            minuteInterval={30}
            onDateChange={this.onDateChange}
          />

     </View>
     <OptionList style={{backgroundColor:'#fff'}} ref="optionType"/>
</ScrollView>

```

**Comment by agrass** [comment]
Great @purnomoeko , I'm going to test your workaround.

someone already solved the bad placement problem (to the right) in Android?

**Comment by alexprice1** [comment]
@purnomoeko ah great. I am on vacation until tomorrow. I will look it tomorrow. Thanks!

**Comment by alexprice1** [comment]
@purnomoeko I tried and this did not fix my problem. @agrass I cannot remember how I got it to work, but the android problem no longer seems to be there.

**Comment by acresta88** [comment]
Changing the background color of the items container works as @purnomoeko said

To change the single item background works as well, here a screenshot to show it: 
![screen shot 2016-04-15 at 11 01 26](https://cloud.githubusercontent.com/assets/2300238/14556650/70375538-02f9-11e6-89da-02ed08a10614.png)

I added a margin of 2 there (the white lines) that actually creates the same problem.

So the main problem there is the padding (in addition to the transparent background of the container), the one in the method:

> const renderedItems = React.Children.map(items, (item) => { ... }

that creates the gap, maybe it should be set as a property? and not have any default padding/margin set. Maybe it should be the same for the items' background colours?

I think the best would be to have as properties:
container background color,
item background color,
paddings/margins for items.

And have default value for the colours (maybe just a white background) and padding/margin set to 0.

**Comment by agrass** [comment]
Great, the other problem of the second image of @alexprice91 (bad placement problem to the right) it's fixed removing this styles that use the example`justifyContent: 'center', alignItems: 'center'` in the main view and changing it for padding or margin.

**Comment by alexprice1** [comment]
Yeah, but I am still seeing an issue with content rendered bellow the list, being placed above the list. (Image 1). I think (Image 2) is just a styling mishap on my end.
