### ISSUE TITLE
Could pass styles to the dropdown

### ISSUE THREAD

**Issue by pickhardt** [alinz/react-native-dropdown#4]
Hey. Thanks for making this. It would be useful if you could pass styles through to the dropdown, or grab them from the props. I might submit a PR once you add a license. This feature seems like something that wouldn't be too hard to add.

**Comment by alinz** [comment]
@pickhardt I have broken this project into multiple files. It would be a lot easier to add a new feature. I have also added the license for this project. Looking forward to see your PR. and sorry for long delay.

**Comment by alinz** [comment]
@pickhardt, 

@averted has added custom style, in this [PR](https://github.com/alinz/react-native-dropdown/pull/7) which I have already merged it into master. You can use 0.0.4 to have this feature.
