### ISSUE TITLE
dropdown list cover by other component

### ISSUE THREAD

**Issue by albertqhd** [alinz/react-native-dropdown#40]
When a component after dropdown,it will cover it.
Any advice?
Thank you very much.

**Comment by samarti** [comment]
Could you provide more info?

**Comment by kevando** [comment]
Putting `<View><Text>HELLO</Text></View>` outside the view container that holds the dropdown will always render over the dropdown.

**Comment by AdamJakiela** [comment]
Make sure you put the `<OptionList ref="OPTIONLIST"/>` tag at the end of the `render()` function.

**Comment by milkersarac** [comment]
Think about zIndex property?

**Comment by abuammar** [comment]
thanks AdamJakiela solved the issue.
