### ISSUE TITLE
Update to latest RN

### ISSUE THREAD

**Issue by ajoshdee** [alinz/react-native-dropdown#44]
Hi, Can you update this to latest RN version?

**Comment by shivamsinha15** [comment]
can you please close this request. There is already PR #41  

until the pull request #41 is accepted you can fix it problem by directly using that specific PR.
1. Goto react project folder
2. rm -rf node_modules
3. npm install https://github.com/g6ling/react-native-dropdown --save
4. npm install

**Comment by itinance** [comment]
It is enough to just remove the react-native-dropdown folder instead of all modules.
1. Go to project folder
2. rm -rf node_modules/react-native-dropdown
3. npm install https://github.com/g6ling/react-native-dropdown --save

:)

**Comment by abuammar** [comment]
thanks itinance
