### ISSUE TITLE
OptionList in ScrollView

### ISSUE THREAD

**Issue by alfondotnet** [alinz/react-native-dropdown#5]
Hi!, 
Thanks for the component, it's very useful!.

I am embedding it into a space-limited view, do you think it would be feasible to put OptionList into a ScrollView so the options are scrollable?

I don't know if you have considered it, meanwhile I'll fork it. Cheers!

**Comment by alinz** [comment]
@alfonsoperez the only thing that you have to do is to put `OptionList` as the last item in your`ScrollView`.

**Comment by alfondotnet** [comment]
Oh, of course, what was I thinking, sorry for that, closing.

**Comment by alinz** [comment]
:+1:
