### ISSUE TITLE
Import React from 'react' rather than 'react-native'

### ISSUE THREAD

**Issue by solittlework** [alinz/react-native-dropdown#51]
Start from React-Native 0.25, react should be imported from 'react' rather then 'react-native'.

**Comment by BTMouseKing** [comment]
I'm having this issue, when will this be fixed please?

**Comment by abuammar** [comment]
i had the same problem,
the solution is 

It is enough to just remove the react-native-dropdown folder instead of all modules.

Go to project folder
rm -rf node_modules/react-native-dropdown
npm install https://github.com/g6ling/react-native-dropdown --save
:)

**Comment by BTMouseKing** [comment]
haha, thanks.

**Comment by KlausBlass** [comment]
abuammar's fix worked for me.

**Comment by heyolajyd** [comment]
@alinz Why is this issue still open. @abuammar and @solittlework seem to have fixed why we're getting the red screen suggesting how to make imports from react-native and react.

**Comment by livein21st** [comment]
@abuammar after trying out the solution, I m getting new error.
I'm just trying to import like this:
import { DropDownBtn } from "react-native-dropdown";
![screenshot_1530026458](https://user-images.githubusercontent.com/8268139/41922496-7ea1dce4-7965-11e8-9401-eaee114c28cc.png)
