### ISSUE TITLE
Dropdown towards the bottom of the screen shows up blank

### ISSUE THREAD

**Issue by dekkofilms** [alinz/react-native-dropdown#55]
Right now I'm putting the dropdown down towards the bottom of the address form, for a user to select a country. However, when I click on the options it is just blank. I realized if I attempted to scroll past the view visible, it is under everything (but not reachable). Right now, I have just copied and pasted the exact code from the README, so any thoughts or help would be appreciated. 

```
          <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center'}}>
            <Select
              width={250}
              ref="SELECT1"
              optionListRef={this._getOptionList.bind(this)}
              defaultValue="Select a Province in Canada ..."
              onSelect={this._canada.bind(this)}>
              <Option value = {{id : "alberta"}}>Alberta</Option>
              <Option>British Columbia</Option>
              <Option>Manitoba</Option>
              <Option>New Brunswick</Option>
              <Option>Newfoundland and Labrador</Option>
              <Option>Northwest Territories</Option>
              <Option>Nova Scotia</Option>
              <Option>Nunavut</Option>
              <Option>Ontario</Option>
              <Option>Prince Edward Island</Option>
              <Option>Quebec</Option>
              <Option>Saskatchewan</Option>
              <Option>Yukon</Option>
            </Select>
            <Text>Selected Canada's province: {this.state.canada}</Text>
            <OptionList ref="OPTIONLIST"/>
          </View>
```

With the appropriate functions needed in the container itself. 

Before click:
<img width="302" alt="screen shot 2017-03-06 at 8 44 10 am" src="https://cloud.githubusercontent.com/assets/14862852/23614607/2272909c-0249-11e7-80ef-18da41b375cf.png">

After click:
<img width="305" alt="screen shot 2017-03-06 at 8 44 16 am" src="https://cloud.githubusercontent.com/assets/14862852/23614616/27a68366-0249-11e7-882f-b59986ccf093.png">

**Comment by sneerin** [comment]
what device are you using, is that samsung device?

**Comment by dekkofilms** [comment]
No, this currently just on an iPhone simulator running as an iPhone 6s

**Comment by RileyDavidson-Evans** [comment]
Have you tried to set the zIndex of the View and container element ?
